
/**
 *
 * @author B00337975 Ian Shaw
 */

import javax.swing.*;

public class PropertyListTestGUI extends javax.swing.JFrame {

    private Boolean addTypeCommercial;

    /**
     * Creates new form PropertyTestGUI
     */
    public PropertyListTestGUI() {
        initComponents();
        final Integer PROPERTY_LIST_SIZE = 10;
        this.propertyList = new PropertyList(PROPERTY_LIST_SIZE);
        this.displayPropertyListTextArea.setText(propertyList.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCommercialButton = new javax.swing.JButton();
        addResidentialButton = new javax.swing.JButton();
        deletePropertyButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayPropertyListTextArea = new javax.swing.JTextArea();
        quitButton = new javax.swing.JButton();
        referenceLabel = new javax.swing.JLabel();
        townLabel = new javax.swing.JLabel();
        rentLabel = new javax.swing.JLabel();
        otherLabel = new javax.swing.JLabel();
        referenceTextField = new javax.swing.JTextField();
        townTextField = new javax.swing.JTextField();
        rentTextField = new javax.swing.JTextField();
        otherTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Property Manager");

        addCommercialButton.setText("Add Commercial Property");
        addCommercialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommercialButtonActionPerformed(evt);
            }
        });

        addResidentialButton.setText("Add Residential Property");
        addResidentialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResidentialButtonActionPerformed(evt);
            }
        });

        deletePropertyButton.setText("Delete a Property");
        deletePropertyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePropertyButtonActionPerformed(evt);
            }
        });

        displayPropertyListTextArea.setColumns(20);
        displayPropertyListTextArea.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        displayPropertyListTextArea.setRows(5);
        jScrollPane1.setViewportView(displayPropertyListTextArea);

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        referenceLabel.setText("Reference");

        townLabel.setText("Town");

        rentLabel.setText("Rent");

        otherLabel.setText("bedrooms or area");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Property");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rentLabel)
                            .addComponent(otherLabel)
                            .addComponent(townLabel)
                            .addComponent(referenceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(referenceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(townTextField)
                            .addComponent(rentTextField)
                            .addComponent(otherTextField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(quitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCommercialButton)
                        .addGap(18, 18, 18)
                        .addComponent(addResidentialButton)
                        .addGap(18, 18, 18)
                        .addComponent(deletePropertyButton)
                        .addGap(0, 242, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCommercialButton)
                    .addComponent(addResidentialButton)
                    .addComponent(deletePropertyButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenceLabel)
                    .addComponent(referenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(townLabel)
                    .addComponent(townTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentLabel)
                    .addComponent(rentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otherLabel)
                    .addComponent(otherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(quitButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        propertyList.savePropertyList();
        JOptionPane.showMessageDialog(null, "Quitting Program...", "Shut Down Message", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void addCommercialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommercialButtonActionPerformed
        // set the type of property to be added
        this.addTypeCommercial = true;
        this.otherLabel.setText("Area");
        // display the interactive elements
        displayAddPropertyInteractiveElements();
    }//GEN-LAST:event_addCommercialButtonActionPerformed

    private void addResidentialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResidentialButtonActionPerformed
        // set the type of property to be added
        this.addTypeCommercial = false;
        this.otherLabel.setText("Bedrooms");
        // display the interactive elements
        displayAddPropertyInteractiveElements();
    }//GEN-LAST:event_addResidentialButtonActionPerformed

    private void displayAddPropertyInteractiveElements() {
        this.referenceLabel.setVisible(true);
        this.townLabel.setVisible(true);
        this.rentLabel.setVisible(true);
        this.otherLabel.setVisible(true);
        this.referenceTextField.setVisible(true);
        this.townTextField.setVisible(true);
        this.rentTextField.setVisible(true);
        this.otherTextField.setVisible(true);
        this.submitButton.setVisible(true);
    }

    private void deletePropertyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePropertyButtonActionPerformed
        this.referenceLabel.setVisible(true);
        this.referenceTextField.setVisible(true);
        this.deleteButton.setVisible(true);
    }//GEN-LAST:event_deletePropertyButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Boolean tryAgain = false;
        try {
            if (this.addTypeCommercial) {
                this.propertyList.addCommercialProperty(
                        this.referenceTextField.getText(),
                        this.townTextField.getText(),
                        Integer.parseInt(this.rentTextField.getText()),
                        Integer.parseInt(this.otherTextField.getText())
                );
            } else {
                this.propertyList.addResidentialProperty(
                        this.referenceTextField.getText(),
                        this.townTextField.getText(),
                        Integer.parseInt(this.rentTextField.getText()),
                        Integer.parseInt(this.otherTextField.getText())
                );
            }
        } catch (PropertyList.arrayFullException error) {
            JOptionPane.showMessageDialog(errorPopup,
                    "The property array is full.\n\nError type: " + error,
                    "Array error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (PropertyList.propertyReferenceNotUnique error) {
            JOptionPane.showMessageDialog(errorPopup,
                    "That property reference is already in use.\n\nError type: " + error,
                    "Reference Uniqueness error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (PropertyList.rentNotWithinBounds error) {
            JOptionPane.showMessageDialog(errorPopup,
                    "The rent must be over 100 and under 1000.\n\nError type: " + error,
                    "Rent out of bounds error",
                    JOptionPane.ERROR_MESSAGE);
            this.rentTextField.setText("");
            tryAgain = true;
        } catch (Exception error) {
            JOptionPane.showMessageDialog(errorPopup,
                    "Error type: " + error,
                    "Unspecified error",
                    JOptionPane.ERROR_MESSAGE);
            tryAgain = true;
        }
        // hide interactive elements
        if (!tryAgain) {
            this.referenceLabel.setVisible(false);
            this.townLabel.setVisible(false);
            this.rentLabel.setVisible(false);
            this.otherLabel.setVisible(false);
            this.referenceTextField.setVisible(false);
            this.townTextField.setVisible(false);
            this.rentTextField.setVisible(false);
            this.otherTextField.setVisible(false);
            this.submitButton.setVisible(false);
            // blank out the text fields for next time
            this.referenceTextField.setText("");
            this.townTextField.setText("");
            this.rentTextField.setText("");
            this.otherTextField.setText("");
            // display the new property list
            this.displayPropertyListTextArea.setText(this.propertyList.toString());
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            propertyList.deleteProperty(this.referenceTextField.getText());
        } catch (PropertyList.propertyReferenceNotFoundException error) {
            JOptionPane.showMessageDialog(errorPopup,
                    "This property reference was not found.\n\nError type: " + error,
                    "Deletion error",
                    JOptionPane.ERROR_MESSAGE);
        }

        // blank out the text field and hide the interactive elements
        this.referenceTextField.setText("");
        this.referenceLabel.setVisible(false);
        this.referenceTextField.setVisible(false);
        this.deleteButton.setVisible(false);
        // display the new property list
        this.displayPropertyListTextArea.setText(this.propertyList.toString());
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PropertyListTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PropertyListTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PropertyListTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PropertyListTestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PropertyListTestGUI propertyTest = new PropertyListTestGUI();
                propertyTest.setVisible(true);
                propertyTest.displayPropertyListTextArea.setEditable(false);
                propertyTest.setDefaultCloseOperation(0);
                propertyTest.referenceLabel.setVisible(false);
                propertyTest.townLabel.setVisible(false);
                propertyTest.rentLabel.setVisible(false);
                propertyTest.otherLabel.setVisible(false);
                propertyTest.referenceTextField.setVisible(false);
                propertyTest.townTextField.setVisible(false);
                propertyTest.rentTextField.setVisible(false);
                propertyTest.otherTextField.setVisible(false);
                propertyTest.submitButton.setVisible(false);
                propertyTest.deleteButton.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCommercialButton;
    private javax.swing.JButton addResidentialButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deletePropertyButton;
    private javax.swing.JTextArea displayPropertyListTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel otherLabel;
    private javax.swing.JTextField otherTextField;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel referenceLabel;
    private javax.swing.JTextField referenceTextField;
    private javax.swing.JLabel rentLabel;
    private javax.swing.JTextField rentTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel townLabel;
    private javax.swing.JTextField townTextField;
    // End of variables declaration//GEN-END:variables
    private final PropertyList propertyList;
    private final JFrame errorPopup = new JFrame("Error Message");
}
